version: "2.4"
services:
  db:
    container_name: lockermat-test-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER:     admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB:       lockermat
    ports:
      - "5434:5432"
    volumes:
      - ./.pg_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lockermat"]
      interval: 3s
      timeout: 5s
      retries: 5