FROM maven:3.9.8-eclipse-temurin-21-alpine AS builder
WORKDIR /opt/lockermat
COPY pom.xml mvnw .mvn/ ./
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests -B

FROM amazoncorretto:21-alpine-jdk
WORKDIR /opt/lockermat
COPY --from=builder /opt/lockermat/target/lockermat-backend.jar ./app.jar
ENTRYPOINT ["java","-jar","app.jar"]