export const GET_LOCKERMAT_POINTS = 'GET_LOCKERMAT_POINTS';
export const SET_LOCKERMAT_POINTS = 'SET_LOCKERMAT_POINTS';
export const SET_INPUT_VALUES = 'SET_INPUT_VALUES';
export const CHANGE_VIEW = 'CHANGE_VIEW';
export const SHOW_POPUP = 'SHOW_POPUP';
